/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controladores.ControladorProducto;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Producto;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Domenika Delgado
 */
public class ListarProducto extends javax.swing.JInternalFrame {

    private ControladorProducto controladorProducto;
   
    /**
     * Creates new form ListarProductos
     */
    
    public ListarProducto(ControladorProducto controladorProducto) {
        initComponents(); 
        this.controladorProducto = controladorProducto;
        llenarDatos();
    }

    
     public void llenarDatos(){
        //Se obtiene el modelo
        DefaultTableModel modelo = (DefaultTableModel) tblProducto.getModel();
        //Se Obtiene la lista del ControladorCliente
        //Es un arreglo de objects
        Set<Producto> lista = controladorProducto.getLista();
        for(Producto producto : lista){
            
            
            //Separo por comas
            Object [] datos = {producto.getCodigo(),//Primera columna con el codigo
                    producto.getNombre(),//Primera columna con el nombre
                    producto.getPrecio()};
    
        //Añadir al modelo, paso los datos
        //por cada iteracion añade una fila
        modelo.addRow(datos);
    }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProducto;
    // End of variables declaration//GEN-END:variables
}
