/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.controladores.ControladorProducto;

/**
 *
 * @author Domenika Delgado
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    //Cliente
    private VentanaCrearCliente crearCliente;
    private VentanaActualizarCliente vac;
    private VentanaEliminarCliente vec;
    
    //Producto
    private VentanaCrearProducto vcp;
    private VentanaBuscarProducto vbp;
    private VentanaActualizarProducto vap;
    private VentanaEliminarProducto vep;
    
    
    //Controladores
    private ControladorCliente controladorCliente;
    private ControladorProducto controladorProducto;
    /**
     * Creates new form VentanaPrincipal
     */
     
     
    public VentanaPrincipal() {
        initComponents();
         controladorCliente = new ControladorCliente();
         controladorProducto = new ControladorProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        ClienteMenu = new javax.swing.JMenu();
        CrearCliente = new javax.swing.JMenuItem();
        BuscarCliente = new javax.swing.JMenuItem();
        AcutalizarCliente = new javax.swing.JMenuItem();
        EliminarCliente = new javax.swing.JMenuItem();
        ListarCliente = new javax.swing.JMenuItem();
        ProductoMenu = new javax.swing.JMenu();
        CrearProducto = new javax.swing.JMenuItem();
        BuscarProducto = new javax.swing.JMenuItem();
        ActualizarProducto = new javax.swing.JMenuItem();
        EliminarProducto = new javax.swing.JMenuItem();
        ListarProducto = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane.setToolTipText("");

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        ClienteMenu.setText("Cliente");

        CrearCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CrearCliente.setText("Crear");
        CrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearClienteActionPerformed(evt);
            }
        });
        ClienteMenu.add(CrearCliente);

        BuscarCliente.setText("Buscar");
        BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteActionPerformed(evt);
            }
        });
        ClienteMenu.add(BuscarCliente);

        AcutalizarCliente.setText("Actualizar");
        AcutalizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcutalizarClienteActionPerformed(evt);
            }
        });
        ClienteMenu.add(AcutalizarCliente);

        EliminarCliente.setText("Eliminar");
        EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteActionPerformed(evt);
            }
        });
        ClienteMenu.add(EliminarCliente);

        ListarCliente.setText("Listar");
        ListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClienteActionPerformed(evt);
            }
        });
        ClienteMenu.add(ListarCliente);

        jMenuBar1.add(ClienteMenu);

        ProductoMenu.setText("Producto");

        CrearProducto.setText("Crear");
        CrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearProductoActionPerformed(evt);
            }
        });
        ProductoMenu.add(CrearProducto);

        BuscarProducto.setText("Buscar");
        BuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProductoActionPerformed(evt);
            }
        });
        ProductoMenu.add(BuscarProducto);

        ActualizarProducto.setText("Actualizar");
        ActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProductoActionPerformed(evt);
            }
        });
        ProductoMenu.add(ActualizarProducto);

        EliminarProducto.setText("Eliminar");
        EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoActionPerformed(evt);
            }
        });
        ProductoMenu.add(EliminarProducto);

        ListarProducto.setText("Listar");
        ListarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarProductoActionPerformed(evt);
            }
        });
        ProductoMenu.add(ListarProducto);

        jMenuBar1.add(ProductoMenu);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
                 //*******************CLIENTE*******************\\ 
    
    //Para Crear un cliente nuevo - se abra otra ventana
    private void CrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearClienteActionPerformed
        // TODO add your handling code here:
        if(crearCliente == null || !crearCliente.isVisible()){
            crearCliente = new VentanaCrearCliente(controladorCliente);
            crearCliente.setVisible(true);
            jDesktopPane.add(crearCliente);
        }
    }//GEN-LAST:event_CrearClienteActionPerformed

    //Para eliminar un cliente - se abra otra ventana
    private void EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClienteActionPerformed
        // TODO add your handling code here:
        if( vec == null || !vec.isVisible()){
        vec = new VentanaEliminarCliente(controladorCliente);
        vec.setVisible(true);
        jDesktopPane.add(vec);
        
           
        }
       
    }//GEN-LAST:event_EliminarClienteActionPerformed

    //Para buscar los datos de un cliente - se abra otra ventana
    private void BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteActionPerformed
        // TODO add your handling code here:
        VentanaBuscarCliente buscarCliente = new VentanaBuscarCliente(controladorCliente);
        buscarCliente.setVisible(true);
        jDesktopPane.add(buscarCliente);
    }//GEN-LAST:event_BuscarClienteActionPerformed

    //Para listat todos los clientes que fueron creados - se abra otra ventana
    private void ListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClienteActionPerformed
        // TODO add your handling code here:
        ListarClientes listarCliente = new ListarClientes(controladorCliente);
        listarCliente.setVisible(true);
        jDesktopPane.add(listarCliente);
    }//GEN-LAST:event_ListarClienteActionPerformed

    //Para actualizar datos de un cliente - se abra otra ventana
    private void AcutalizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcutalizarClienteActionPerformed
        // TODO add your handling code here:
        if(vac == null || !vac.isVisible()){
        vac = new VentanaActualizarCliente(controladorCliente);
        vac.setVisible(true);
        jDesktopPane.add(vac);
        //VentanaActualizarCliente.cambiarIdioma(localizacion);
        }
    }//GEN-LAST:event_AcutalizarClienteActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    
                          //*******************PRODUCTO*******************\\ 
    
    //Crear un producto 
    private void CrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProductoActionPerformed
        // TODO add your handling code here:
         if (vcp == null || !vcp .isVisible()) {
            vcp  = new VentanaCrearProducto(controladorProducto);
            vcp .setVisible(true);
            jDesktopPane.add(vcp );
        }
    }//GEN-LAST:event_CrearProductoActionPerformed

    //Buscar producto por su codigo
    private void BuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProductoActionPerformed
        // TODO add your handling code here:
        if(vbp == null || !vbp.isVisible()){
        vbp = new VentanaBuscarProducto(controladorProducto);
        vbp.setVisible(true);
        jDesktopPane.add(vbp);
        }
    }//GEN-LAST:event_BuscarProductoActionPerformed

    //Actualizar datos del producto
    private void ActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProductoActionPerformed
        // TODO add your handling code here:
        if(vap == null || !vap.isVisible()){
        vap = new VentanaActualizarProducto(controladorProducto);
        vap.setVisible(true);
        jDesktopPane.add(vap);
        }
    }//GEN-LAST:event_ActualizarProductoActionPerformed

    //Eliminar un producto
    private void EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoActionPerformed
        // TODO add your handling code here:
        if(vep == null || !vep.isVisible()){
        vep = new VentanaEliminarProducto(controladorProducto);
        vep.setVisible(true);
        jDesktopPane.add(vep);
    }//GEN-LAST:event_EliminarProductoActionPerformed
    
    }
    //Listar todos los productos
    private void ListarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarProductoActionPerformed

    
    

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarProducto;
    private javax.swing.JMenuItem AcutalizarCliente;
    private javax.swing.JMenuItem BuscarCliente;
    private javax.swing.JMenuItem BuscarProducto;
    private javax.swing.JMenu ClienteMenu;
    private javax.swing.JMenuItem CrearCliente;
    private javax.swing.JMenuItem CrearProducto;
    private javax.swing.JMenuItem EliminarCliente;
    private javax.swing.JMenuItem EliminarProducto;
    private javax.swing.JMenuItem ListarCliente;
    private javax.swing.JMenuItem ListarProducto;
    private javax.swing.JMenu ProductoMenu;
    private javax.swing.JMenu Salir;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
